config/routes.rb
Fantasyxi::Application.routes.draw do

  root :to => "Players#index"

  match "/auth/facebook/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout

  match "leagues/:id/join" => "leagues#join"
  match "leagues/:id/leave" => "leagues#leave"
  match "leagues/:id/remove_user" => "leagues#remove_user"
  match "leagues/:id/accept" => "leagues#accept"
  match "leagues/:id/decline" => "leagues#decline"

  match "user_teams/:id/spy" => "user_teams#spy"

  resources :players
  resources :leagues

  resources :users
  resources :user_teams

  match 'player_info' => 'user_teams#player_info'
  match 'change_formation' => 'user_teams#change_formation'
  match 'save_team' => 'user_teams#save_team'
  match 'undo_substitution' => 'user_teams#undo_substitution'

  match 'send_invite' => 'leagues#send_invite'

end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
	belongs_to :user
	has_many :user_team_stats

	has_many :acquisitions
	has_many :players, :through => :acquisitions
	has_many :substitutions

end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController

	helper_method :sort_column, :sort_direction, :team_id, :positions, :low_boundary, :high_boundary

	def index
		@user = User.all.sort! { |a,b| b.user_teams.map(&:points).reduce(:+) <=> a.user_teams.map(&:points).reduce(:+)}
	end

	def spy
			@user_team = UserTeam.find(params[:id])
			@user = User.find(@user_team.user_id)
			
			@points = @user.user_teams.map(&:points).inject(0, :+)

			@bank = 11_000_000 - @user_team.players.map(&:price).inject(0, :+)

		
		if team_id.to_i > 0
			@players = Player.joins(:player_stats)
			.select("players.*, sum(player_stats.points) as points").group("players.id")
			.search(params[:search]).where(:team_id => team_id, :position => positions, :price =>low_boundary..high_boundary).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
		else

			@players = Player.joins(:player_stats)
			.select("players.*, sum(player_stats.points) as points").group("players.id")
			.search(params[:search]).where(:position => positions, :price =>low_boundary..high_boundary)
			.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
		end

	end

	def show

	flash[:notice] = "Dra spelare fraan listan till hoeger."

	if current_user
		if not current_user.user_teams.empty?
			@user_team = UserTeam.find(params[:id])

			
			# Ska man få ändra laget eller inte?
			is_owner = current_user.id == @user_team.user_id

			redirect_to :action => :spy, :controller => :user_teams if not is_owner

			@points = current_user.user_teams.map(&:points).inject(0, :+)

			@bank = 11_000_000 - @user_team.players.map(&:price).inject(0, :+)
		else
			@user_team = UserTeam.new
		end

		
		# Filtrerat på land
		if team_id.to_i > 0
			@players = Player.joins(:player_stats)
			.select("players.*, sum(player_stats.points) as points").group("players.id")
			.search(params[:search]).where(:team_id => team_id, :position => positions, :price =>low_boundary..high_boundary).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
		else

			@players = Player.joins(:player_stats)
			.select("players.*, sum(player_stats.points) as points").group("players.id")
			.search(params[:search]).where(:position => positions, :price =>low_boundary..high_boundary)
			.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
		end

		@sub_hash = []
		@user_team.substitutions.each do |s|
			hash = Hash.new
			#player_in = Player.joins(:team).select('players.*, teams.name as country').where(:id => s.player_in)
			#player_out = Player.joins(:team).select('players.*, teams.name as country').where(:id => s.player_out)
			player_in = Player.find(s.player_in)
			player_out = Player.find(s.player_out)
			hash['player_in'] = player_in
			hash['player_out'] = player_out
			hash['position'] = s.position
			@sub_hash.push(hash)
		end
	end
	end

	def player_info
		@player = Player.joins(:player_stats)
				.select("players.* 
					, sum(player_stats.points) as sum_points
					, sum(player_stats.red) as sum_red
					, sum(player_stats.yellow) as sum_yellow
					, sum(player_stats.assists) as sum_assists
					, sum(player_stats.goals) as sum_goals")
				.where(:id => params[:player_id])
				.group("players.id")
				.first

		@player_round = Player.find(params[:player_id]).player_stats
	end

	def save_team

		flash[:notice] = "Ditt lag har uppdaterats"

		if current_user.user_teams.first.name == nil
			6.times do |round|
				current_user.user_teams[round].update_attributes(:name => params[:teamname])
			end
			flash[:notice] = "Ditt lag har skapats"
		end

		@user_team = current_user.user_teams[current_round - 1]

		@points = current_user.user_teams.map(&:points).inject(0, :+)
		@bank = 11_000_000 - @user_team.players.map(&:price).inject(0, :+)

		@user_team.players.destroy_all
		j = ActiveSupport::JSON
		teamplayers = j.decode(params[:teamplayers])
		substitutions = j.decode(params[:substitutions])
		undo_sub_pos = j.decode(params[:undo_sub_pos])

		teamplayers.each do |player|
			p = Player.find(player['id'])
			@user_team.players.push(p)
		end
		@user_team.substitutions.destroy_all

		substitutions.each do |sub|
			@user_team.substitutions.push(Substitution.create(:player_in => sub['player_in']['id'], :player_out => sub['player_out']['id'], :position => sub['position']))
		end

			undo_sub_pos.each do |pos|
				@user_team.substitutions.where(:position => pos).destroy_all
			end
	end

	def undo_substitution
		#user_team = current_user.user_teams[0];
		#user_team.substitutions.where(:position => params[:position]).destroy_all

		redirect_to user_teams_path
	end

	private

	def team_id
		params[:team_id] || nil
	end

	def positions
		if not (params[:gk_check] || params[:df_check] || params[:mf_check] || params[:fw_check])
			return ["GK", "DF","MF","FW"] 
		end

		pos = []

		if(params[:gk_check])
			pos.push "GK"
		end
		if(params[:df_check])
			pos.push "DF"
		end
		if(params[:mf_check])
			pos.push "MF"
		end
		if(params[:fw_check])
			pos.push "FW"
		end

		return pos
	end

	def low_boundary
		params[:low_boundary] || 0
	end

	def high_boundary
		params[:high_boundary] || 11_000_000
	end
  


  def sort_column
  	params[:sort] || "name"
  end
  
  def sort_direction
  	params[:direction] || "asc"
  end

end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/views/user_teams/_detailed_info.html.erb
<div class="modal" id="infoModal" >
	<div class="modal-header">
		<a class="close btn close_modal" data-dismiss="modal">x</a>
		<h3><div id="player_name"></div></h3>
	</div>
	<div class="modal-body">
		
		<div class="row">
			<div class="span3">
				<div id="info_kit">
				</div>
			</div>
			<div class="span3">
				<h2>Statistik</h2>
				<table class="table table-striped table-bordered table-condensed">
						<tr>
							<td>Omgång:</td>
							<td>1</td>
							<td>2</td>
							<td>3</td>
							<td>4</td>
							<td>5</td>
							<td>6</td>
							<td>tot</td></tr>

						<tr id="table_points">
							<td>Poäng:</td>
							<td class="round_0"></td>
							<td class="round_1"></td>
							<td class="round_2"></td>
							<td class="round_3"></td>
							<td class="round_4"></td>
							<td class="round_5"></td>
							<td></td></tr>

						<tr id="table_goals">
							<td>Mål:</td>
							<td class="round_0"></td>
							<td class="round_1"></td>
							<td class="round_2"></td>
							<td class="round_3"></td>
							<td class="round_4"></td>
							<td class="round_5"></td>
							<td></td></tr>

						<tr id="table_assists">
							<td>Assist:</td>
							<td class="round_0"></td>
							<td class="round_1"></td>
							<td class="round_2"></td>
							<td class="round_3"></td>
							<td class="round_4"></td>
							<td class="round_5"></td>
							<td></td></tr>

						<tr id="table_yellow">
							<td>Gula:</td>
							<td class="round_0"></td>
							<td class="round_1"></td>
							<td class="round_2"></td>
							<td class="round_3"></td>
							<td class="round_4"></td>
							<td class="round_5"></td>
							<td></td></tr>

						<tr id="table_red">
							<td>Röda:</td>
							<td class="round_0"></td>
							<td class="round_1"></td>
							<td class="round_2"></td>
							<td class="round_3"></td>
							<td class="round_4"></td>
							<td class="round_5"></td>
							<td></td></tr>
				</table>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<a class="btn close_modal" data-dismiss="modal">Stäng</a>
	</div>
</div>

app/views/user_teams/_pickplayers.html.erb
<table id="players_table" class="table table-bordered table-condensed">
	<script> handleMarked();</script>
<span>
<thead>
<tr>
	<th><%= sortable "name", "Namn"%></th>
	<th><%= sortable "price", "Pris"%></th>
	<th><%= sortable "position", "Position"%></th>
	<th><%= sortable "team_id", "Land"%></th>
	<th><%= sortable "points", "Poäng"%></th>
	<th></th>
</thead>
<tbody>
<% @players.each do |player| %>
	<tr draggable="true" id=<%="player_#{player.id}"%> >
	<td><%= player.name %></td>
	<td><%= player.price %></td>
	<td><%= player.position %></td>
	<td><%= Team.find(player.team_id).name %></td>
	<td><%= player.points %></td>

	<td class="not-disabled"><%= link_to 'info', {:controller => :user_teams, :action => :player_info, :player_id => player.id} , {"data-toggle" => "modal" , :class => "btn btn-mini btn-info",:remote => true} %>
	</tr>
</span>
<% end %>
</tbody>
</table>
<%= will_paginate @players ,:inner_window => 2, :previous_label => "«", :next_label => '»', :renderer => PaginationListLinkRenderer %>

<div id="info">
<%= render 'detailed_info' %>
</div>

app/views/user_teams/_pitch.html.erb
		<div id="goalie">
			<div class="player player_0" data-position="0">
				<div class="kit"></div>
				<div class="player_name"></div>
			</div>
		</div>
		
		<div id="defense">
			<% 4.times do |i|  %>
				<div class="player player_<%=i+1 %>" data-position="<%=i+1 %>">
					<div class="kit"></div>
					<div class="player_name"></div>
				</div>
			<% end %>
		</div>
		
		<div id="midfield">
			<% 4.times do |i|  %>
				<div class="player player_<%=i+5 %>" data-position="<%=i+5 %>">
					<div class="kit"></div>
					<div class="player_name"></div>
				</div>
			<% end %>
		</div>
		
		<div id="forwards">
			<% 	2.times do |i|  %>
				<div class="player player_<%=i+9 %>" data-position="<%=i+9 %>">
					<div class="kit"></div>
					<div class="player_name"></div>
				</div>
			<% end %>
		</div>

app/views/user_teams/change_formation.js.erb
/*function countPlayers(players) {
	num_players = 0;
	$.each(players, function(i,p) {
		if(p) num_players++;
	});

	return num_players;
}

teamplayers = $.parseJSON($("#teamplayers").val());



if(teamplayers && (countPlayers(teamplayers["DF"]) > <%= params[:def].to_i %>) ||
	(countPlayers(teamplayers["MF"]) > <%= params[:mid].to_i %>)||
	(countPlayers(teamplayers["FW"]) > <%= params[:for].to_i %>)) {
	alert("Noo!");
}
else {
	$("#pitch").html("<%= escape_javascript(render("pitch"))%>");

$.each(teamplayers["GK"], function(index, player) {
	var kit = $("#goalie .gk_0 .kit");
	var player_name = $("#goalie .gk_0 .player_name");

	var kit_url = '/assets/kits/thumbs/' + player.country.toLowerCase() + 'thumb.png';
	var name = player.name.replace(" ", "\n");

			$(kit).css('background-image',"url('" + kit_url + "')");
			$(player_name).text(name);

});

var player_position = 0;

$.each(teamplayers["DF"], function(index, player) {
	if(player) {

	var kit = $("#defense .df_" + player_position +  " .kit");
	var player_name = $("#defense .df_" + player_position + " .player_name");

	var kit_url = '/assets/kits/thumbs/' + player.country.toLowerCase() + 'thumb.png';
	var name = player.name.replace(" ", "\n");

			$(kit).css('background-image',"url('" + kit_url + "')");
			$(player_name).text(name);


	teamplayers["DF"][player_position] = player;
		player_position++
	}

});

var player_position = 0;
$.each(teamplayers["MF"], function(index, player) {
	if(player) {
		var kit = $("#midfield .mf_" + player_position +  " .kit");
		var player_name = $("#midfield .mf_" + player_position + " .player_name");

		var kit_url = '/assets/kits/thumbs/' + player.country.toLowerCase() + 'thumb.png';
		var name = player.name.replace(" ", "\n");

				$(kit).css('background-image',"url('" + kit_url + "')");
				$(player_name).text(name);


		teamplayers["MF"][player_position] = player;
		player_position++
	}

});

var player_position = 0;
$.each(teamplayers["FW"], function(index, player) {
	if(player) {
	var kit = $("#forwards .fw_" + player_position +  " .kit");
	var player_name = $("#forwards .fw_" + player_position + " .player_name");

	var kit_url = '/assets/kits/thumbs/' + player.country.toLowerCase() + 'thumb.png';
	var name = player.name.replace(" ", "\n");

			$(kit).css('background-image',"url('" + kit_url + "')");
			$(player_name).text(name);

	teamplayers["FW"][player_position] = player;
	}
	player_position++

});

$("#teamplayers").text(JSON.serialize(teamplayers));
}
*/

app/views/user_teams/index.html.erb
<div class="well">
<h1>Highscore</h1>

<table class="table table-striped table-bordered table-condensed">
			<thead><tr>
				<th></th>
				<th>Namn</th>
				<th>Manager</th>
				<th>Poäng</th>
			</tr></thead >

<% @user.each_with_index do |user, i| %>
			<tbody><tr>
				<td><%= i +1 %></td>
				<td><%= link_to user.user_teams.first.name, user_team_path(user.user_teams[current_round-1].id) %></td>
				<td><%= user.name %></td>
				<td><%= user.user_teams.map(&:points).reduce(:+) %></td>
			</tr></tbody>
<% end %>
</div>

app/views/user_teams/player_info.js.erb
// Renderar modal med detaljerad information
$("#info").html("<%= escape_javascript(render("detailed_info"))%>");
$(".modal-header #player_name").html("<%= @player.name %>");
$("#info_kit").html('<%= image_tag "kits/#{Team.find(@player.team_id).name.downcase!}.png" %>');
$("#infoModal").css('display',"block");
$("#infoModal .close_modal").click(function(){
		$("#infoModal").css('display',"none");
	});
$("#table_points td:last").html("<%= @player.sum_points %>");
$("#table_goals td:last").html("<%= @player.sum_goals %>");
$("#table_assists td:last").html("<%= @player.sum_assists %>");
$("#table_yellow td:last").html("<%= @player.sum_yellow %>");
$("#table_red td:last").html("<%= @player.sum_red %>");

// Gå igenom alla rundor
<% 6.times do |i| %>

$("#table_points .round_" + <%=i%>).html("<%= @player_round[i].points %>");
$("#table_goals .round_" + <%=i%>).html("<%= @player_round[i].goals %>");
$("#table_assists .round_" + <%=i%>).html("<%= @player_round[i].assists %>");
$("#table_yellow .round_" + <%=i%>).html("<%= @player_round[i].yellow %>");
$("#table_red .round_" + <%=i%>).html("<%= @player_round[i].red %>");

<% end %>

app/views/user_teams/save_team.js.erb
// Uppdaterar flashen
$("#pitch_alert").html("<%= flash[:notice] %>");
$("#pitch_alert").css('display','block');
$("#pitch_alert").addClass('alert-success');
$("#pitch_alert").removeClass('alert-info');
$("#pitch_alert").removeClass('alert-danger');

// Uppdaterar lagnamn
$('#user_team_name').html("<h1><%= current_user.user_teams[0].name %>");

/*$.each(teamplayers, function(i, position) {
	$.each(position, function(j, player) {
	 	if(player) {
	 		$.get('/change_formation');
	 	}
	});
});*/

app/views/user_teams/show.html.erb
<% if current_user %>	
	<div class="row">
		<div class="span6">
			<div class="well">
				<div id="header_row">
					<% if current_user.user_teams.first.name %>
					  	<div id="user_team_name">
					  	<h1><%= @user_team.name %></h1>
					  </div>
					  <h2>Poäng: <%= @points %></h2>
					  <div class="clear"></div>
						<h3 id="bank" ><%= @bank %></h3>
					  <% else %>
						<h1><input id="name_input" value="Namn"/></h1>
					<% end %>
					</div>
		    	<div id="pitch_alert" class="alert alert-info"><%= flash[:notice] %></div>
				<div id="pitch">
				<%= render 'pitch' %>
				</div>
				<div id="save_button_div">
				<%= form_for(@user_team, :remote => true, :url => save_team_path, :html => {:id => 'save_form'}) do |f| %>
				<input type="hidden" name="teamplayers" id="teamplayers" value="<%= @user_team.players.to_json %>" />
				<input type="hidden" name="substitutions" id="substitutions" value="<%= @sub_hash.to_json %>" />
				<input type="hidden" name="teamname" id="teamname_hidden" value="<%= @user_team.name %>" />
				<input type="hidden" name="undo_sub_pos" id="undo_sub_pos" value="[]" />
				<%= f.submit("Spara Laget", :id => 'save_button',:class => 'btn btn-warning')%>
				</div>
			<% end %>
			</div>
		</div>
		<div class="span6">
			<div class="well">
			<h2>Byten</h2>
			<div id="subs">
			</div>
			</div>
		</div>
		<div class="span6">
			<%= form_tag @user_team, :method => 'get', :id => "players_search", :class => "form-inline" do %>

				<%= hidden_field_tag :direction, params[:direction] %>
				<%= hidden_field_tag :sort, params[:sort] %>
				<%= hidden_field_tag :team_id, params[:team_id] %>
				<%= hidden_field_tag :positions, positions %>
				<%= hidden_field_tag :low_boundary ,low_boundary %>
				<%= hidden_field_tag :high_boundary ,high_boundary %>

				<div id="filter_settings" class="well">
				<div id="search_teamselect">
				<label>Sök</label>
				<%= text_field_tag :search, params[:search] %>
				<label>Lag</label>
				<%= select_tag "team_id", options_from_collection_for_select(Team.all,'id','name')  , {:prompt => "Alla länder" }%>
				</div>
				<div id="position_select">
					<ul>
						<li><%= check_box_tag 'gk_check',"gk_check", true, :id=> 'gk_check', :class => "position_check" %>
						<%= label_tag 'gk_check', 'Målvakter' %></li>
						<li><%= check_box_tag 'df_check',"df_check", true, :id=> 'df_check', :class => "position_check" %>
						<%= label_tag 'df_check', 'Backar' %></li>
						<li><%= check_box_tag 'mf_check',"mf_check", true, :id=> 'mf_check', :class => "position_check" %>
						<%= label_tag 'mf_check', 'Mittfältare' %></li>
						<li><%= check_box_tag 'fw_check',"fw_check", true, :id=> 'fw_check', :class => "position_check" %>
						<%= label_tag 'fw_check', 'Anfallare' %></li>
					</ul>

				</div>
				<div id="slider"></div>
				<label id="low_boundary_label">0</label>
				<label id="high_boundary_label">0</label>
				</div>

				<div id="players" class="well" ><%= render 'pickplayers' %>


				</div>
			<% end %>
		</div>	
	</div><!-- /row -->
	<div class="row">
		<div class="span6" id="user_team_form" >
		</div>
	</div><!-- /row -->
<% end %>

app/views/user_teams/show.js.erb
	$("#players").html("<%= escape_javascript(render("pickplayers"))%>");
	
	// Kopplar drag-event till de nya spelarna i listan
	$("#players #players_table tr").each(function(index, player) {
			$(player).bind('dragstart', handleDragStart);
	});

		// Om ingen position har valts ska inget visas
		if(!($("#positions").val())) {
			$('#players_table tbody').html("");
			$('.pagination').html("");
		}
	

app/views/user_teams/spy.html.erb
<div class="row">
		<div class="span6">
			<div class="well">


	<div id="header_row">
<% if not current_user.user_teams.empty? %>
 <div id="user_team_name"> <h1><%= @user_team.name %></h1></div><h2>Poäng: <%= @points %></h2>
  <div class="clear"></div>
  <h3 id="bank" ><%= @bank %></h3>
  <% else %>
	<h1><input id="name_input" value="Namn"/></h1>
<% end %>
</div>
			<div id="pitch">
			<%= render 'pitch' %>
			</div>
		</div>	
	</div><!-- /row -->
	<div class="row">
		<div class="span6">
				<input type="hidden" name="teamplayers" id="teamplayers" value="<%= @user_team.players.to_json %>" />
		</div>
	</div></div>