config/routes.rb
Fantasyxi::Application.routes.draw do

  root :to => "Players#index"

  match "/auth/facebook/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout

  match "leagues/:id/join" => "leagues#join"
  match "leagues/:id/leave" => "leagues#leave"
  match "leagues/:id/remove_user" => "leagues#remove_user"
  match "leagues/:id/accept" => "leagues#accept"
  match "leagues/:id/decline" => "leagues#decline"

  match "user_teams/:id/spy" => "user_teams#spy"

  resources :players
  resources :leagues

  resources :users
  resources :user_teams

  match 'player_info' => 'user_teams#player_info'
  match 'change_formation' => 'user_teams#change_formation'
  match 'save_team' => 'user_teams#save_team'
  match 'undo_substitution' => 'user_teams#undo_substitution'

  match 'send_invite' => 'leagues#send_invite'

end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team
	has_many :player_stats

	has_many :acquisitions
	has_many :user_teams, :through => :acquisitions

	def self.search(search)
	  if search
	   where('name LIKE ?', "%#{search}%")
	  else
	    scoped
	  end
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	helper_method :sort_column, :sort_direction
				

	def index
		#@players = Player.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 20, :page => params[:page])
		
		if not params[:round]
			@players = Player.joins(:player_stats)
				.select("players.* 
					, sum(player_stats.points) as points
					, sum(player_stats.red) as red
					, sum(player_stats.yellow) as yellow
					, sum(player_stats.assists) as assists
					, sum(player_stats.goals) as goals")
				.group("players.id")
				.search(params[:search])
				.order(sort_column + " " + sort_direction)
				.paginate(:per_page => 20, :page => params[:page])
		else
			 @players = Player.joins(:player_stats)
			 	.select("players.* 
			 		, player_stats.points as points
			 		, player_stats.goals as goals
			 		, player_stats.assists as assists
			 		, player_stats.red as red
			 		, player_stats.yellow as yellow")
			 	.group("players.id")
			 	.where(:player_stats => {:round => params[:round]})
			 	.search(params[:search])
			 	.order(sort_column + " " + sort_direction)
				.paginate(:per_page => 20, :page => params[:page])
		end


		@player = Player.new
	end

	def show
		if not params[:round]
			@player = Player.joins(:player_stats)
				.select("players.* 
					, sum(player_stats.points) as points
					, sum(player_stats.red) as red
					, sum(player_stats.yellow) as yellow
					, sum(player_stats.assists) as assists
					, sum(player_stats.goals) as goals")
				.where(:id => params[:id])
				.group("players.id")
				.first
		else
			 @player = Player.joins(:player_stats)
			 	.select("players.* 
			 		, player_stats.points as points
			 		, player_stats.goals as goals
			 		, player_stats.assists as assists
			 		, player_stats.red as red
			 		, player_stats.yellow as yellow")
			 	.group("players.id")
			 	.where(:player_stats => {:round => params[:round]}, :id => params[:id])
				.first
		end
	end

	def new
		@player = Player.new
	end

	def create
  		p = Player.create params[:player]
  		redirect_to :back
  	end

  private
  
  def sort_column
  	params[:sort] || "name"
  end
  
  def sort_direction
  	params[:direction] || "asc"
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_players.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<div class="span9">
  		<div class="well">
			<table class="table table-striped table-bordered table-condensed">
				<thead><tr>
					<th><%= sortable "name", "Namn"%></th>
					<th><%= sortable "team_id", "Lag" %></th>
					<th><%= sortable "points" , "Poäng" %></th>
					<th><%= sortable "goals" , "Mål" %></th>
					<th><%= sortable "assists" %></th>	
					<th><%= sortable "yellow" , "Gula" %></th>
					<th><%= sortable "red" , "Röda" %></th>		
				</tr></thead >

			<% for player in @players %>

				<tbody><tr>
					<td><%= link_to player.name, player_path(player)  %></td>
					<td><%= Team.find(player.team_id).name %></td>
					<td><%= player.points %></td>
					<td><%= player.goals %></td>
					<td><%= player.assists %></td>
					<td><%= player.yellow %></td>
					<td><%= player.red %></td>

				</tr></tbody>
			<% end %>

			</table>
			<%= will_paginate @players, :renderer => PaginationListLinkRenderer %>
</div>
</div>

app/views/players/index.html.erb
<div class="row">
<div class="span3">
  <div class="well">
    <h1>Sök Spelare</h1>

    <%= form_tag players_path, :method => 'get', :id => "players_search" do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
      </p>

     <!--	<div class="btn-group">
      		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        	Omgång
        	<span class="caret"></span>
      		</a>
      		<ul class="dropdown-menu">
    	    	<li><a href="?round=1">Runda 1</a></li>
    	  	</ul>
    	</div> -->

      <ul class="nav nav-pills">
            <li class="dropdown" id="menu1">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                Omgång
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="?round=1">Omgång 1</a></li>
                <li><a href="?round=2">Omgång 2</a></li>
                <li><a href="?round=3">Omgång 3</a></li>
                <li><a href="?round=4">Kvartsfinal</a></li>
                <li><a href="?round=5">Semifinal</a></li>
                <li><a href="?round=6">Final</a></li>
                <li class="divider"></li>
                <li><%= link_to "Totalt", players_path %></li>
              </ul>
            </li>
          </ul>
  </div>
</div>

  <div id="players"><%= render 'players' %></div>
<% end %>
</div>

app/views/players/index.js.erb
$("#players").html("<%= escape_javascript(render("players"))%>")

app/views/players/new.html.erb
<h1>Ny Spelare</h1>

<%= form_for @player do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :team_id %>
	<%= f.text_field :team_id %>
	<%= f.submit %>
<% end %>

app/views/players/show.html.erb
<div class="span7"><div class="well">
<%= hidden_field_tag :round, params[:round] %>
<h1><%= @player.name %></h1>
<div class="row">
	<div class="span3">
		<%= image_tag "kits/#{Team.find(@player.team_id).name.downcase!}.png" %>
	</div>
	<div class="span3">
		<h2>Statistik</h2>

		<ul class="nav nav-pills">
			  <li class="dropdown" id="menu1">
			    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
			      Omgång
			      <b class="caret"></b>
			    </a>
			    <ul class="dropdown-menu">
			      <li><%= link_to "Omgång 1", player_path(@player, :round => 1)  %></li>
			      <li><%= link_to "Omgång 2", player_path(@player, :round => 2)  %></li>
			      <li><%= link_to "Omgång 3", player_path(@player, :round => 3)  %></li>
			      <li><%= link_to "Kvartsfinal", player_path(@player, :round => 4)  %></li>
			      <li><%= link_to "Semifinal", player_path(@player, :round => 5)  %></li>
			      <li><%= link_to "Final", player_path(@player, :round => 6)  %></li>
			      <li class="divider"></li>
			      <li><%= link_to "Totalt", player_path(@player)  %></li>
			    </ul>
			  </li>
			</ul>

		<table class="table table-striped table-bordered table-condensed">
		<tr><td>Namn:</td><td><%= @player.name %></td></tr>
				<tr><td>Poäng:</td><td><%= @player.points %></td></tr>
				<tr><td>Mål:</td><td><%= @player.goals %></td></tr>
				<tr><td>Assist:</td><td><%= @player.assists %></td></tr>
				<tr><td>Gula:</td><td><%= @player.yellow%></td></tr>
				<tr><td>Röda:</td><td><%= @player.red %></td></tr>
		</table>
	</div>
</div>
</div>
</div>