config/routes.rb
Fantasyxi::Application.routes.draw do

  root :to => "Players#index"

  match "/auth/facebook/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout

  match "leagues/:id/join" => "leagues#join"
  match "leagues/:id/leave" => "leagues#leave"
  match "leagues/:id/remove_user" => "leagues#remove_user"
  match "leagues/:id/accept" => "leagues#accept"
  match "leagues/:id/decline" => "leagues#decline"

  match "user_teams/:id/spy" => "user_teams#spy"

  resources :players
  resources :leagues

  resources :users
  resources :user_teams

  match 'player_info' => 'user_teams#player_info'
  match 'change_formation' => 'user_teams#change_formation'
  match 'save_team' => 'user_teams#save_team'
  match 'undo_substitution' => 'user_teams#undo_substitution'

  match 'send_invite' => 'leagues#send_invite'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyXI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body onload ="handleMarked()">

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Fantasy XI</a>

        <% if current_user %>

        <div class="nav-collapse">
          <ul class="nav pull-left">
            <% if current_user %>
            <li><%= link_to "Mitt Lag", current_user.user_teams.first %></li>
          <% end %>
            <li class="dropdown">
		    <a href="#"
		          class="dropdown-toggle"
		          data-toggle="dropdown">
              <% has_invites = (not current_user.invites.empty?) %>
             <% invite_count = current_user.invites.count %>
		          Ligor <%= content_tag(:span, invite_count,:class => 'badge') if has_invites %>
		          <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
          <% if current_user && user_leagues.length > 0 %>
          <% user_leagues.each do |league| %>
            <li><%= link_to league.name , league %></li>
          <% end %>
            <li class="divider"></li>
          <% end %>
          <li><%= link_to "Alla ligor" , leagues_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Skapa liga" , new_league_path %></li>
          <% if has_invites %>
          <li class="divider"></li>
            <li class="nav-header">Inbjudningar</li>
            <% current_user.invites.each do |invite| %>
            <% league = League.find(invite.league_id) %>
            <li><%= link_to league.name , league_path(league, :invited => true) %></li>
          <% end %>
          <% end %>
		    </ul>
		  </li>

            <li><%= link_to "Ranking" , user_teams_path %></li>
            <li><%= link_to "Statistik", players_path %></li>
        </ul>


      <% end %> 
            <ul class="nav pull-right"><li><a href="#"><%= current_user.name if current_user %></a></li>
            <li>

              <% if current_user %>
                <%= link_to "Logga Ut", logout_path %>
              <% else %>
                <%= link_to "Logga In", "auth/facebook" %>
              <% end %> 
            </li></ul>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="container"><%= yield %></div>
</body>
</html>